---
title: Hands-on training session 5
subtitle: BLCM models for continuous tests
date: "`r Sys.Date()`"
author:
  - Sonja Hartnack
  - Eleftherios Meletis
theme: metropolis
aspectratio: 43
colortheme: seahorse
header-includes: 
  - \input{preamble}
params:
  presentation: TRUE
output:
  beamer_presentation:
      pandoc_args: ["-t", "beamer"]
      slide_level: 2
  html_document: default
---

```{r rendering, eval=FALSE, include=FALSE}
# To render this as PDF (beamer) slides run:
rmarkdown::render('Adv5_ContinuousTests.Rmd', 'beamer_presentation', params=list(presentation=TRUE))
# And for html:
rmarkdown::render('Adv5_ContinuousTests.Rmd', 'html_document', params=list(presentation=FALSE))
```

```{r setup, include=FALSE}
# Reduce the width of R code output for PDF only:
if(params$presentation) options(width=60)
knitr::opts_chunk$set(echo = TRUE)

library('runjags')
runjags.options(silent.jags=TRUE)
```


# Session 5:  BLCM models for continuous tests

## Overview

Date/time:

  - 21st February 2020
  - 14.00 - 15.30

Teachers:

  - Sonja Hartnack (presenter)
  - Eleftherios Meletis

## Slide


## Exercise

Instructions here

